name: 'Detox CI Tests'
on: [push]

jobs:
  tests:
    name: 'Running tests'
    runs-on: 'macOS-latest'
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12.6
      - name: Setup - Install Homebrew
        run: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      - name: Setup - Install Android Emulator
        run: |
          touch ~/.android/repositories.cfg
          brew cask install android-sdk
          brew cask install intel-haxm
          sdkmanager --update
          export ANDROID_SDK_ROOT="/usr/local/share/android-sdk"
          yes | sdkmanager "platform-tools" "platforms;android-27" "extras;intel;Hardware_Accelerated_Execution_Manager" "build-tools;27.0.0" "system-images;android-27;google_apis;x86" "emulator"
          yes | avdmanager create avd -n test -k "system-images;android-27;google_apis;x86" --tag google_apis
      - name: List Android Emulators
        run: emulator -list-avds
      - name: List iOS Simulators
        run: xcrun simctl list
      - name: Setup - Install Yarn
        run: brew install yarn --ignore-dependencies
      - name: Setup - Install NPM Dependencies
        run: yarn
      - name: Setup - Install CocoaPods CLI
        run: sudo gem install cocoapods
      - name: Setup - Install Detox and deps
        run: |
          brew tap wix/brew
          brew install applesimutils
          yarn global add react-native-cli
          yarn global add detox-cli
      - name: Run tests
        run: yarn ci
